######################################################### TOOLCHAIN VERSIONING #########################################
ARG MULTISTAGE_BUILDER_VERSION
ARG UBUNTU_VERSION=22.01
ARG DOCKER_VERSION=
ARG KUBECTL_VERSION
ARG HELM_VERSION
ARG TERRAFORM_VERSION
ARG AZ_CLI_VERSION
ARG ANSIBLE_VERSION
ARG POWERSHELL_VERSION
ARG KUBELOGIN_VERSION
ARG ZSH_VERSION

FROM mcr.microsoft.com/devcontainers/base:ubuntu-$UBUNTU_VERSION AS final

ARG USERNAME=vscode


ARG PKGS="\
gnupg \
software-properties-common \
ncat\
"

RUN apt update && \
    apt install --no-install-recommends -y ${PKGS} && \
    apt upgrade -y && \
    apt autoremove --purge -y


## Install `az` (Azure CLI)
COPY ./files/scripts/install-azure-cli.sh /tmp
RUN sh /tmp/install-azure-cli.sh

## Install Terraform
COPY ./files/scripts/install-terraform.sh /tmp
RUN sh /tmp/install-terraform.sh

## Install Terragrunt
COPY ./files/scripts/install-terragrunt.sh /tmp
RUN sh /tmp/install-terragrunt.sh

## Install Docker
COPY ./files/scripts/install-docker.sh /tmp
RUN sh /tmp/install-docker.sh

## Install Ansible
COPY ./files/scripts/install-ansible.sh /tmp
RUN sh /tmp/install-ansible.sh

## Install Helm
COPY ./files/scripts/install-helm.sh /tmp
RUN sh /tmp/install-helm.sh

## Install PowerShell
COPY ./files/scripts/install-powershell.sh /tmp
RUN sh /tmp/install-powershell.sh


## Cleanup
#RUN rm -rf /tmp/*

USER $USERNAME
